// src/App.vue
<template>
  <div id="app" class="app">
    <form 
      @submit.prevent
      class="app__form"
    >
      <form-section
        :title="sections[0].title"
        :fields="sections[0].fields"
        @onTriggerRefresh="onTriggerRefresh"
        @onRefreshField="onRefreshField"
      >
      </form-section>

      <form-section
        :title="sections[1].title"
        :fields="sections[1].fields"
        :total="totalExistingIncome"
        @onRefreshField="onRefreshField"
      >
      </form-section>

      <section class="form-section">
        <span class="form-section__title">Pension Target</span>

        <number-field
          v-model.number="portionToFill.value"
          :label="portionToFill.label"
          :placeholder="portionToFill.placeholder"
          :type="portionToFill.type"
        >
        </number-field>

        <total-field
          :label="'Retirement Income Gap'"
          :value="retirementIncomeGap">
        </total-field>
      </section>
    </form>

    <div class="app__chart">
      <header class="app__chart__header">
        <h1 class="app__chart__title">Personal Pension Target</h1>
        <span class="app__chart__number">${{ personalPensionTarget | prettyNumber }}</span>
      </header>

      <chart
        :total="chartData.total"
        :data="chartData.bars"
        :xLabel="chartData.xLabel"
      >
      </chart>
    </div>
  </div>
</template>

<script>
import FormSection from './components/FormSection.vue'
import TotalField from './components/TotalField.vue'
import NumberField from './components/NumberField.vue'
import Chart from './components/Chart.vue'

export default {
  name: 'app',

  data: () => ({
    sections: [
      {
        title: 'General Information',
        fields: [
          { label: 'Retirement Age', value: 70, placeholder: '70', autofocus: true, triggerRefresh: true },
          { label: 'Spouse Retirement Age', value: 71, placeholder: '71', disabled: true },
          { label: 'Retirement Income Goal', value: 28000, placeholder: '28000', refreshable: true, showRefresh: false, type: 'currency' }
        ]
      },
      {
        title: 'Existing Income Sources',
        fields: [
          { label: 'Social Security', value: 9000, placeholder: '9000', refreshable: true, showRefresh: false, type: 'currency' },
          { label: 'Spouse Social Security', value: 9000, placeholder: '9000', refreshable: true, showRefresh: false, type: 'currency' },
          { label: 'Other Income Source(s)', value: 0, placeholder: '0', type: 'currency' }
        ]
      }
    ],
    portionToFill: { label: 'Portion To Fill', value: 100, placeholder: '100%', type: 'percent' },
  }),

  components: {
    FormSection,
    TotalField,
    NumberField,
    Chart
  },

  computed: {
    totalExistingIncome () {
      const existingIncomeSources = this.sections[1].fields
      const value = existingIncomeSources.reduce((previous, current) => {
        let previousValue = previous.value || previous
        previousValue = previousValue || 0
        const currentValue = current.value || 0
        return parseInt(previousValue) + currentValue
      })
      return { label: 'Total Existing Income', value: value }
    },
    retirementIncomeGap () {
      const retirementIncomeGoal = this.sections[0].fields[2].value
      return Math.max(retirementIncomeGoal - this.totalExistingIncome.value, 0)
    },
    personalPensionTarget () {
      return Math.round(this.retirementIncomeGap * (this.portionToFill.value / 100))
    },
    chartData () {
      const retirementIncomeGoal = this.sections[0].fields[2].value
      const retirementAge = this.sections[0].fields[0].value
      const retirementIncomeGap = this.portionToFill.value < 100 ? this.retirementIncomeGap : 0
      return {
        total: retirementIncomeGoal,
        xLabel: retirementAge,
        bars:[
          { name: 'Retirement Income Gap', value: retirementIncomeGap, order: 1 },
          { name: 'Personal Pension Target', value: this.personalPensionTarget, order: 2 },
          { name: 'Total Existing Income', value: this.totalExistingIncome.value, order: 3 }
        ]
      }
    }
  },

  methods: {
    onTriggerRefresh () {
      this.sections.forEach((section) => {
        section.fields.forEach((field) => {
          if (field.refreshable) {
            field.showRefresh = true
          }
        })
      })
    },

    onRefreshField (data) {
      const sectionIndex = this.sections.findIndex(section => section.title === data.sectionTitle)
      const section = this.sections[sectionIndex]
      const fieldIndex = section.fields.findIndex(field => field.label === data.fieldLabel)
      const rangeMax = 5000
      const randomAmount = Math.floor(Math.random() * (rangeMax - -rangeMax + 1)) + -rangeMax;
      this.sections[sectionIndex].fields[fieldIndex].showRefresh = false
      this.sections[sectionIndex].fields[fieldIndex].value += randomAmount
    }
  }
}
</script>

<style lang="scss">
@import './scss/_variables.scss';
@import './scss/_functions.scss';

html {
  font: {
    family: $sans-serif;
    size: 20px;
  }
}

body {
  margin: 0;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
}

.app {
  color: palette(black);
  display: flex;
  min-height: 100vh;

  @media screen and (max-width: screen(large)) {
    flex-direction: column;
  }

  &__form, &__chart {
    flex: 1;
    padding: 2rem;
  }
}

.app__chart {
  display: flex;
  flex-direction: column;

  &__header {
    align-items: center;
    display: flex;
    flex-direction: column;
  }

  &__title {
    font: {
      size: 1rem;
      weight: 600;
    }
    margin: {
      top: 0;
      bottom: 1.5rem;
    }
  }

  &__number {
    color: palette(blue);
    font: {
      size: 4rem;
      weight: 400;
    }
    letter-spacing: 3px;
  }
}
</style>

// reactjs/src/App.js
import React, { Component } from 'react'
import { formatValue, toNumber } from './utils'
import './App.css'

import FormSection from './components/FormSection'
import NumberField from './components/NumberField.jsx'
import TotalField from './components/TotalField.jsx'
import Chart from './components/Chart.jsx'

class App extends Component {
  state = {
    retirementAge: { label: 'Retirement Age', value: 70, placeholder: '70', autofocus: true, triggerRefresh: true },
    spouseRetirementAge: { label: 'Spouse Retirement Age', value: 71, placeholder: '71', disabled: true },
    retirementIncomeGoal: { label: 'Retirement Income Goal', value: 28000, placeholder: '28000', refreshable: true, showRefresh: false, type: 'currency' },
    socialSecurity: { label: 'Social Security', value: 9000, placeholder: '9000', refreshable: true, showRefresh: false, type: 'currency' },
    spouseSocialSecurity: { label: 'Spouse Social Security', value: 9000, placeholder: '9000', refreshable: true, showRefresh: false, type: 'currency' },
    otherIncomeSources: { label: 'Other Income Source(s)', value: 0, placeholder: '0', type: 'currency' },
    portionToFill: { label: 'Portion To Fill', value: 100, placeholder: '100%', type: 'percent' }
  }

  totalExistingIncome (existingIncomeSources) {
    const value = existingIncomeSources.reduce((previous, current) => {
      let previousValue = previous.value || previous
      previousValue = previousValue || 0
      const currentValue = current.value || 0
      return toNumber(previousValue) + toNumber(currentValue)
    })
    return { label: 'Total Existing Income', value: value }
  }

  retirementIncomeGap (retirementIncomeGoal, totalExistingIncome) {
    return Math.max(toNumber(retirementIncomeGoal) - totalExistingIncome, 0)
  }

  personalPensionTarget (retirementIncomeGap) {
    return Math.round(retirementIncomeGap * (toNumber(this.state.portionToFill.value) / 100))
  }

  handleChange (target) {
    let field = this.state[target.name]
    field.value = target.value
    this.setState({[target.name]: field})
  }

  handleTriggerRefresh () {
    Object.keys(this.state).forEach((key) => {
      let field = this.state[key]
      if (field.refreshable) {
        field.showRefresh = true
        this.setState({[key]: field})
      }
    })
  }

  handleRefreshField (name) {
    let field = this.state[name]
    const rangeMax = 2000
    const randomAmount = Math.floor(Math.random() * (rangeMax + rangeMax + 1)) - rangeMax
    field.value = formatValue(Math.max(toNumber(field.value) + randomAmount, 0), field.type)
    field.showRefresh = false
    this.setState({[name]: field})
  }

  renderForm (sections, retirementIncomeGap, personalPensionTarget) {
    return (
      <form className="app__form">
        {
          sections.map((section) =>
            <FormSection
              key={section.title}
              title={section.title}
              fields={section.fields}
              total={section.total}
              handleChange={this.handleChange.bind(this)}
              handleTriggerRefresh={this.handleTriggerRefresh.bind(this)}
              handleRefreshField={this.handleRefreshField.bind(this)}
            >
            </FormSection>
          ) 
        }

        <section className="form-section">
          <span className="form-section__title">Pension Target</span>

          <TotalField
            label={'Retirement Income Gap'}
            value={retirementIncomeGap}
            grandTotal={false}
          >
          </TotalField>

          <NumberField
            label={this.state.portionToFill.label}
            value={this.state.portionToFill.value}
            placeholder={this.state.portionToFill.placeholder}
            type={this.state.portionToFill.type}
            handleChange={this.handleChange.bind(this)}
          >
          </NumberField>

          <TotalField
            label={'Personal Pension Target'}
            value={personalPensionTarget}
            grandTotal={true}
          >
          </TotalField>
        </section>
      </form>
    )
  }

  render () {
    const existingIncomeSources = [this.state.socialSecurity, this.state.spouseSocialSecurity, this.state.otherIncomeSources]
    const totalExistingIncome = this.totalExistingIncome(existingIncomeSources)
    const retirementIncomeGap = this.retirementIncomeGap(this.state.retirementIncomeGoal.value, totalExistingIncome.value)
    const personalPensionTarget = this.personalPensionTarget(retirementIncomeGap)
    const sections = [
      {
        title: 'General Information',
        fields: [this.state.retirementAge, this.state.spouseRetirementAge, this.state.retirementIncomeGoal]
      },
      {
        title: 'Existing Income Sources',
        fields: existingIncomeSources,
        total: totalExistingIncome
      }
    ]
    const chartData = {
      total: toNumber(this.state.retirementIncomeGoal.value),
      xLabel: `Age ${this.state.retirementAge.value}`,
      bars:[
        { name: 'Retirement Income Gap', value: toNumber(this.state.portionToFill.value) < 100 ? retirementIncomeGap : 0, order: 1 },
        { name: 'Personal Pension Target', value: personalPensionTarget, order: 2 },
        { name: 'Total Existing Income', value: totalExistingIncome.value, order: 3 }
      ]
    }

    return (
      <div className="app">
        {this.renderForm(sections, retirementIncomeGap, personalPensionTarget)}

        <div className="app__chart">
          <header className="app__chart__header">
            <h1 className="app__chart__title">Personal Pension Target</h1>
            <span className="app__chart__number">{formatValue(personalPensionTarget)}</span>
            <span>per month</span>
          </header>

          <Chart
            total={chartData.total}
            data={chartData.bars}
            xLabel={chartData.xLabel}
          >
          </Chart>
        </div>
      </div>
    )
  }
}

export default App
