// reactjs/src/components/FormSection.jsx
import React, { Component } from 'react';

import NumberField from './NumberField.jsx'
import TotalField from './TotalField.jsx'

class FormSection extends Component {
  renderFields () {
    return this.props.fields.map((field) =>
      <NumberField
        key={field.label}
        label={field.label}
        autofocus={field.autofocus}
        disabled={field.disabled}
        placeholder={field.placeholder}
        refreshable={field.refreshable}
        showRefresh={field.showRefresh}
        triggerRefresh={field.triggerRefresh}
        type={field.type}
      >
      </NumberField>
    );
  };

  renderTotal () {
    if (this.props.total) {
      return (
        <TotalField
          label={this.props.total.label}
          value={this.props.total.value}
        >
        </TotalField>
      );
    }
  };

  render () {
    return (
      <section className="form-section">
        <span
          className="form-section__title">
          { this.props.title }
        </span>

        { this.renderFields() }
        { this.renderTotal() }
      </section>
    );
  }
}

export default FormSection;

// vuejs/src/components/FormSection.vue
<template>
  <section class="form-section">
    <span
      v-if="title"
      class="form-section__title">
      {{ title }}
    </span>
    
    <number-field
      v-for="field in fields"
      v-model="field.value"
      :key="field.label"
      :label="field.label"
      :autofocus="field.autofocus"
      :disabled="field.disabled"
      :placeholder="field.placeholder"
      :refreshable="field.refreshable"
      :showRefresh="field.showRefresh"
      :triggerRefresh="field.triggerRefresh"
      :type="field.type"
      @onRefreshField="onRefreshField"
      @onTriggerRefresh="onTriggerRefresh"
    >
    </number-field>

    <total-field
      v-if="total"
      :label="total.label"
      :value="total.value"
    >
    </total-field>
  </section>
</template>

<script>
import NumberField from './NumberField.vue'
import TotalField from './TotalField.vue'

export default {
  name: 'form-section',

  components: {
    NumberField,
    TotalField
  },

  props: {
    title: String,
    fields: { type: Array, required: true },
    total: Object
  },

  methods: {
    onInput (value) {
      console.log(value)
      this.$emit('input', value)
    },

    onTriggerRefresh () {
      this.$emit('onTriggerRefresh')
    },

    onRefreshField (fieldKey) {
      this.$emit('onRefreshField', fieldKey)    
    }
  }
}
</script>

<style lang="scss">
@import '../scss/_variables.scss';
@import '../scss/_functions.scss';

.form-section {
  display: flex;
  flex-direction: column;
  margin-bottom: 1.5rem;

  &__title {
    color: palette(black);
    font: {
      size: 1rem;
      weight: 600;
    }
    margin-bottom: .5rem;

    @media screen and (max-width: screen(medium)) {
      font-size: .9rem;
    }
  }
}
</style>
